title: Fairness, Privacy, Artifical Intelligence
description: > # this means to ignore newlines until "baseurl:"
  A blog by Alycia N. Carey
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Alycia N. Carey # add your name
author-img: C567FDAB-9691-4E05-A2FB-2A6A8D7F748A_1_105_c.jpeg # add your photo
about-author: A blog by Alycia N. Carey # add description
social-twitter: alycia_noel_ # add your Twitter handle
social-github: alycia-noel # add your Github handle
social-linkedin: alyciacarey # add your Linkedin handle
social-email: ancarey@uark.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
