title: Fairness, Privacy, Artificial Intelligence
description: > # this means to ignore newlines until "baseurl:"
  A blog by Alycia N. Carey
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Alycia N. Carey # add your name
author-img: 4677C153-4EC5-4AA5-B172-8F3584B5869D_1_101_o.jpeg # add your photo
about-author: I am a third year Distinguished Doctoral Fellow in computer science at the University of Arkansas. My work focuses on fair and private federeated learning. # add description
social-twitter: alycia_noel_ # add your Twitter handle
social-github: alycia-noel # add your Github handle
social-linkedin: alyciacarey # add your Linkedin handle
social-email: ancarey@uark.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
